//different schools' LTW cash/commit + liftime cash/committ

sum lifetime_cash if ugrad_school=="CSOM"
sum lifetime_cash if ugrad_school=="CSON"
sum lifetime_cash if ugrad_school=="LSOE"
sum lifetime_cash if ugrad_school=="MCAS"
sum lifetime_cash if ugrad_school=="NC"
sum lifetime_cash if ugrad_school=="WCAS"
sum lifetime_commit if ugrad_school=="CSOM"
sum lifetime_commit if ugrad_school=="CSON"
sum lifetime_commit if ugrad_school=="LSOE"
sum lifetime_commit if ugrad_school=="MCAS"
sum lifetime_commit if ugrad_school=="NC"
sum lifetime_commit if ugrad_school=="WCAS"
sum ltw_cash if ugrad_school=="CSOM"
sum ltw_cash if ugrad_school=="CSON"
sum ltw_cash if ugrad_school=="LSOE"
sum ltw_cash if ugrad_school=="MCAS"
sum ltw_cash if ugrad_school=="NC"
sum ltw_cash if ugrad_school=="WCAS"
sum ltw_commit if ugrad_school=="CSOM"
sum ltw_commit if ugrad_school=="CSON"
sum ltw_commit if ugrad_school=="LSOE"
sum ltw_commit if ugrad_school=="MCAS"
sum ltw_commit if ugrad_school=="NC"
sum ltw_commit if ugrad_school=="WCAS"

